Добавлены JPA классы. Работа приложения переделана под них
MadraySha2/java-shareit pull request #3
Opened 2023-05-21 16:29 UTC by MadraySha2

2023-05-21 21:24 UTC, MadraySha2 commented
Привет!
Знаю, что не оч правильно делить на папки внутри, могу убрать, но в букинге совсем дико выглядело без деления. А потом решил, что раз там сделал, то и везде сделаю :)

2023-05-22 13:35 UTC, TomattmanYandex requested changes
Много вопросов по стилю кода, намного меньше по функционалу

2023-05-22 13:35 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
Воу воу, 
круто

2023-05-22 13:35 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
но похоже не используется, тогда зачем?

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +package ru.practicum.shareit.booking.model;
с той стркутурой пакетов, как используется в этом проекте, обычно не выделяют подпакеты под какой то отдельный функционал, все что касается букинга в пакете букинг без подпакетов

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingDto.getStart().isEqual(bookingDto.getEnd())
метод очень тяжело читается
как сделать это легче
1) в начале сделать все проверки, а потом уже начать действия, а то сейчас одна проверка одно действие, потом снова проверка которая также может все сломать
2) проверки которые в блоках if  вынести в отдельные методы
например
вместо 
if (bookingDto.getStart().isEqual(bookingDto.getEnd()) || bookingDto.getStart().isAfter(bookingDto.getEnd()))
throw new NotAvailableException("Incorrect date!");
        }
сделать validateBookingDate(bookingDto)
а в сам метод поместить все содержимое метода
и так далее 
второй вариант как сделать это по другому (тут не так подойдет как могло бы)
это вместо 
if (bookingDto.getStart().isEqual(bookingDto.getEnd()) || bookingDto.getStart().isAfter(bookingDto.getEnd()))
сделать
if(isBookingDateNotValid(bookingDto))
а в самом методе 
return bookingDto.getStart().isEqual(bookingDto.getEnd()) || bookingDto.getStart().isAfter(bookingDto.getEnd())

за счет того, что не надо пытаться понять что в условии, и само условие можно понять по имени метода, читается гораздо проще

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public List<BookingDto> getAllBookingByState(Long id, String state, Integer type) throws Throwable {
что за type в параметре
(и то что появился этот вопрос, это не призыв к ответу, а призыв к изменению кода)
разбить этот метод на два, только с двумя параметрами, и вызывать нужный из уровня контроллера, и не будет никакой путаницы
сразу и понятнее станет, и методы станут покороче, следовательно понимать их станет проще

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +package ru.practicum.shareit.item.model;
по поводу пакетов я уже писал, но тут можно добавить, ведь тут пример того, когда подпакет бы пригодился
т.е. есть пакет item в нем все классы касающиеся айтемов а в нем уже подпакет comment и в нем все что касается коментариев, так как коментарии это часть айтемов

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Autowired
зачем тут эти аннотации, все заинжектится по конструктору

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getOwner().getId().longValue() == userId.longValue()) {
вот тут всю эту конструкцию внутри if можно было бы вынести в отдельный метод

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public CommentDto addComment(Long userId, Long itemId, CommentDto commentDto) {
я бы сделал отдельный сервис для комментариев и вынес бы логику комментариев туда

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDto setComments(ItemDto itemDto) {
да и это тоже кажется что лучше бы воспринималось как отдельный метод 
List<CommentDto> getComents(long itemId)
а уже там где айтему проставляются комменты вместо вызова этого метода - itemDto.setComments(getComments(itemDtro.getId())
Ведь метод который нам возвращает комменты нам с большей вероятностью пригодится, чем метод который проставляет их в дто
А еще этот метод можно было бы вынести в CommentService

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +package ru.practicum.shareit.user.dto;
по поводу пакетов уже писал

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return toUserDto(userRepository.save(toUser(user)));
а уникальность email никак не провврфется?

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +import ru.practicum.shareit.user.dto.UserDto;
не могу саму строчку прокоментить но при обновлении юзера надо передать UserDto

2023-05-22 13:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserDto updateUser(Long userId, User user) {
принимаем userDto тут и в контроллере

2023-05-22 13:43 UTC, MadraySha2 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return toUserDto(userRepository.save(toUser(user)));
Привет! Проверяется на уровне бд, потому как, если проверять ее тут, валятся тесты на юзера, сам не очень понимаю, почему так, но оно так

2023-05-23 13:57 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return toUserDto(userRepository.save(toUser(user)));
Я уже с кем то из вашей группы обсуждал, что тесты постмана не самsе лучшие тут, что в них проверяется сгенерированный id

2023-05-23 13:58 UTC, TomattmanYandex approved these changes
Принято

2023-06-07 00:39 UTC, merged