Add item requests
MadraySha2/java-shareit pull request #5
Opened 2023-06-07 16:38 UTC by MadraySha2

2023-06-08 14:36 UTC, TomattmanYandex requested changes
Привет хорошая работа, есть пара вопросов по стилю кода
иногда есть впечатление что разные части писали разные люди, стоит сделать одинаково

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size < 0) {
и эта проверка и @PositiveOrZero в параметрах, что то лишнее кажется

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                PageRequest.of(from > 0 ? from / size : 0, size, Sort.by(Sort.Direction.DESC, "start")));
PageRequest лучше сделать на слое сервиса, и снова какие то лишние проверки

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size < 0) {
аналогично

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<BookingDto> getAllBookingByState(Long id, String state, Pageable pageable);
лучше чтобы принимал числа и pageble устанавливал на уровне сервиса

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                  @RequestParam(defaultValue = "0") @Min(0) int from,
а тут другая проверка, кажется стоит определиться

2023-06-08 14:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getItems(id, PageRequest.of(from, size));
и снова эту логику лучше в сервис, а еще первый параметр - номер страницы, следовательно тут что то неправильное

2023-06-08 14:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryIntegrationTest.java
> +        User user = User.builder().name("TestUser").email("test@mail.com").build();
в этом и предыдущем методе первые 12 строк одинаковые, может стоит сделать метод который будет создавать эти данные и вызывать его тут

2023-06-08 15:02 UTC, MadraySha2 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size < 0) {
> Привет хорошая работа, есть пара вопросов по стилю кода иногда есть впечатление что разные части писали разные люди, стоит сделать одинаково

Хотел убрать аннотации все аннотации после тестов, но так был этими тестами убит, что забыл...  :)

2023-06-08 20:15 UTC, MadraySha2 commented
Привет!
Вроде все поправил.
Если не трудно, поделись своим опытом, пожалуйста: насколько вообще распространено, что разработчик покрывает свой код тестами ? 
Просто, я пока в небольшой компании работаю, такой необходимости нет, т.к. я вообщем-то один джавист - показываю итоги и тестирую, почти сразу в проде :)

Заранее спасибо за ответ!!

2023-06-09 08:19 UTC, TomattmanYandex requested changes
Перепроверь пожалуйста тот момент что я прокоментил

2023-06-09 08:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Pageable pageable = PageRequest.of(from, size);
разве первый параметр не номер страницы?

2023-06-09 08:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Pageable pageable = PageRequest.of(from, size);
следовательно надо что-то высчитывать

2023-06-09 08:45 UTC, MadraySha2 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Pageable pageable = PageRequest.of(from, size);
Надеюсь, я правильно понял

2023-06-10 09:01 UTC, TomattmanYandex approved these changes
Принято

2023-06-10 17:31 UTC, merged